/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsignRouteImport } from './routes/consign'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CarsIdRouteImport } from './routes/cars.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignRoute = ConsignRouteImport.update({
  id: '/consign',
  path: '/consign',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/cars/$id',
  path: '/cars/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consign': typeof ConsignRoute
  '/editorial': typeof EditorialRoute
  '/inventory': typeof InventoryRoute
  '/cars/$id': typeof CarsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consign': typeof ConsignRoute
  '/editorial': typeof EditorialRoute
  '/inventory': typeof InventoryRoute
  '/cars/$id': typeof CarsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consign': typeof ConsignRoute
  '/editorial': typeof EditorialRoute
  '/inventory': typeof InventoryRoute
  '/cars/$id': typeof CarsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consign' | '/editorial' | '/inventory' | '/cars/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consign' | '/editorial' | '/inventory' | '/cars/$id'
  id: '__root__' | '/' | '/consign' | '/editorial' | '/inventory' | '/cars/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsignRoute: typeof ConsignRoute
  EditorialRoute: typeof EditorialRoute
  InventoryRoute: typeof InventoryRoute
  CarsIdRoute: typeof CarsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consign': {
      id: '/consign'
      path: '/consign'
      fullPath: '/consign'
      preLoaderRoute: typeof ConsignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/cars/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsignRoute: ConsignRoute,
  EditorialRoute: EditorialRoute,
  InventoryRoute: InventoryRoute,
  CarsIdRoute: CarsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
